name: test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v5
      id: setup-python
      with:
        python-version: '3.10'
        cache: 'poetry'
    - run: echo '${{ steps.setup-python.outputs.cache-hit }}' # true if cache-hit occurred on the primary key
    - run: poetry install
    - run: poetry run pytest
